/**
 * Preload script – exposes an empty API surface for now.
 * Later we'll add secure IPC channels (chat, RAG, fine-tune).
 */
console.log("[preload] script loaded");
import { contextBridge, ipcRenderer } from 'electron';

/** Matches backend.model_manager.discovery record */
export type ModelMeta = {
  repo_id: string;
  path: string;
  size_mb: number;
  last_access: string;
};

contextBridge.exposeInMainWorld('api', {
  placeholder: true,

  /** Retrieve the cached-model index generated by the Python backend. */
  listModels: (): Promise<ModelMeta[]> =>
    ipcRenderer.invoke("list-models"),
}); 